# Generated by Django 5.2.5 on 2025-09-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='description',
        ),
    ]
