# Generated by Django 5.2.5 on 2025-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_remove_episode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание серии'),
        ),
    ]
