# Generated by Django 5.2.5 on 2025-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_episode_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, help_text='Загрузите изображение постера', null=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
