# Generated by Django 5.2.5 on 2025-09-07 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_show_poster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Выходит'), ('completed', 'Завершен'), ('upcoming', 'Скоро выйдет')], default='ongoing', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка пользователя')),
                ('rated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='shows.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка пользователя',
                'verbose_name_plural': 'Оценки пользователей',
                'unique_together': {('user', 'show')},
            },
        ),
    ]
