# Generated by Django 5.2.5 on 2025-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_show_country_show_status_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='trailer_id',
            field=models.CharField(blank=True, help_text='ID видео из YouTube (только часть после v=)', max_length=20, null=True, verbose_name='ID YouTube трейлера'),
        ),
    ]
